错误和异常处理
===

---

> 在python中一共有2种错误：一种是语法错误，另外一种是异常。

* ### 语法错误

    ```py
    语法错误也叫做解析错误，是指python无法正确的识别代码的造成的。
    根本原因在于人的行为：手残，脑残和眼残的行为。

    解决方法：按照正确的语法进行书写就没这个错误了！
    ```

* ### 异常

    ```py
    异常是指在语法正确的前提下，程序的报错就是异常。

    它是在程序异常时单独存在的一个对象，可以对其进行获取或其他操作
    ```

* ### 异常的分类

    ```py
    AssertError               断言语句（assert）失败
    AttributeError            尝试访问未知的对象属性
    EOFError                  用户输入文件末尾标志EOF（Ctrl+d）
    FloatingPointError        浮点计算错误
    GeneratorExit             generator.close()方法被调用的时候
    ImportError               导入模块失败的时候
    IndexError                索引超出序列的范围
    KeyError                  字典中查找一个不存在的关键字
    KeyboardInterrupt         用户输入中断键（Ctrl+c）
    MemoryError               内存溢出（可通过删除对象释放内存）
    NameError                 尝试访问一个不存在的变量
    NotImplementedError       尚未实现的方法
    OSError                   操作系统产生的异常（例如打开一个不存在的文件）
    OverflowError             数值运算超出最大限制
    ReferenceError            弱引用（weak reference）试图访问一个已经被垃圾回收机制回收了的对象
    RuntimeError              一般的运行时错误
    StopIteration             迭代器没有更多的值
    SyntaxError               Python的语法错误
    IndentationError          缩进错误
    TabError                  Tab和空格混合使用
    SystemError               Python编译器系统错误
    SystemExit                Python编译器进程被关闭
    TypeError                 不同类型间的无效操作
    UnboundLocalError         访问一个未初始化的本地变量（NameError的子类）
    UnicodeError              Unicode相关的错误（ValueError的子类）
    UnicodeEncodeError        Unicode编码时的错误（UnicodeError的子类）
    UnicodeDecodeError        Unicode解码时的错误（UnicodeError的子类）
    UnicodeTranslateError     Unicode转换时的错误（UnicodeError的子类）
    ValueError                传入无效的参数
    ZeroDivisionError         除数为零
    ```

---
# 常见的错误操作：

* ### IndexError 索引错误

    ```py
    lists = [1,3,6]
    print(lists[3])
    ```

* ### KeyError 键不存在

    ```py
    dicts = {'gp':'高坡','cr':'曹睿','tw':'唐伟'}
    print(dicts['zj'])
    ```

* ### nameError 变量不存在

    ```py
    print(ch)
    ```

* ### AssertError 断言错误

    ```py
    assert 1>0
    assert 3>5
    ```

* ### IndentationError缩进错误

    ```py
    def myfunc():
        print('眼残')
       print('眼残')
    ```

---

# 错误异常处理

* ### 错误异常处理
    ```py
    try:
        # 尝试实现某个操作，
        # 如果没出现异常，任务就可以完成
        # 如果出现异常，将异常从当前代码块扔出去尝试解决异常

    except 异常类型1:
        # 解决方案1：用于尝试在此处处理异常解决问题

    except 异常类型2：
        # 解决方案2：用于尝试在此处处理异常解决问题

    except (异常类型1,异常类型2...)
        # 解决方案：针对多个异常使用相同的处理方式

    excpet:
        # 解决方案：所有异常的解决方案

    else:
        # 如果没有出现任何异常，将会执行此处代码

    finally:
        # 管你有没有异常都要执行的代码
    ```
* ### 处理过程
    ```py
    try:
        # 尝试执行代码区域。
        # 如果没有错误，那就没啥事了，则执行else区域
        # 如果出现错误，抛出错误异常对象，由下面的其他块尝试接受错误

    except 异常类型1:
        # 如果try块扔出的异常类型和当前指定类型一直，那么则当前块接收错误，并且在当前区域给出错误的解决方案。（非必须）
        # 如果try块扔出的异常类型和当前指定类型不一直，则将异常扔到下一个代码块检测

    except 异常类型2:
        # 如果try块扔出的异常类型和当前指定类型一直，那么则当前块接收错误，并且在当前区域给出错误的解决方案。（非必须）
        # 如果try块扔出的异常类型和当前指定类型不一直，则将异常扔到下一个代码块检测

    except 异常类型3:
        # 如果try块扔出的异常类型和当前指定类型一直，那么则当前块接收错误，并且在当前区域给出错误的解决方案。（非必须）
        # 如果try块扔出的异常类型和当前指定类型不一直，则将异常扔到下一个代码块检测

    except (异常类型4，异常类型5，...)
        # 如果try块扔出的异常类型和当前指任意定类型一直，那么则当前块接收错误，并且在当前区域给出错误的解决方案。（非必须）
        # 如果try块扔出的异常类型和当前指定类型不一直，则将异常扔到下一个代码块检测

    except: #所有异常
        # 如果其他except块均不能接受异常对象，那么则当前块接受异常，并且进行处理即可（非必须）

    else:
        # try区域代码没有任何异常，则else区域执行（非必须）

    finally:
        # 无论出现或者不出现异常，当前块都会执行
    ```

---

# 用户自定义错误和自定义抛出错误

* ### 用户自定义异常抛出操作
    ```py
    raise  异常对象
    ```

* ### 用户自定义异常类
    ```py
    class 异常类名(RuntimeError):
        # 定义用户抛出自定义异常对象时可以向对象中传入的内容信息（由用户自己决定）
        def __init__(self,errormsg...):
            # 接收用户创建对象时传入的错误信息，并且存入对象，方便后期使用
            self.errormsg = errormsg
            #...
        pass
    ```

* ### 在try..except中接收异常对象

    ```py
    try:
        #尝试代码执行区域
    except 异常类型 as 异常对象变量:
        #解决方案
    except 异常类型 as 异常对象变量:
        #解决方案
    #....
    ```